functionless/functionless

src/appsync.ts
src/compile.ts

The logic for detecting (and then transforming) `new AppsyncFunction` was naive. It would transform any class named `AppsyncFunction`, which would have conflicted with `@aws-cdk/aws-appsync-alpha`.
As of this change, the compiler now looks for a static property, `FunctionlessType`.
```ts
export class AppsyncFunction {
public static readonly FunctionlessType = "AppsyncFunction";
}
```

fix: detect AppsyncFunction via a static property instead of class name

---

README.md
src/appsync.ts
src/compile.ts
src/function.ts
src/table.ts
src/util.ts
src/vtl.ts
test-app/src/people-db.ts
test/function.test.ts
test/table.test.ts
test/vtl.test.ts

Fixes #24
Fixes #25
This Pull Request makes changes to the type signature and name of an `AppsyncFunction`:
* Renames `AppsyncFunction` to `AppsyncResolver`. This aligns with AWS Appsync's terminology - technically a Resolver is a collection of 0-many Functions. It also addresses some of the naming concerns that are coming as we implement other services such as Step Functions, see https://github.com/sam-goodwin/functionless/issues/7#issuecomment-1057485056
* Changes the type signature to use an `object` to represent the Resolver's arguments instead of a TypeScript function signature and moves them to the `$context.arguments` variable. This aligns `functionless` 1:1 with Appsync's VTL environment (a tenet we are adopting for the whole project) and also aligns with existing GraphQL tooling. …

feat: rename AppsyncFunction to AppsyncResolver and move arguments to $context.arguments

---

src/appsync.ts
src/expression.ts
src/statement.ts
src/vtl.ts
test/function.test.ts
test/table.test.ts
test/util.ts
test/vtl.test.ts

There were some bugs in how we synthed VTL:
1. if-statements occurring after the last service call were ignored.
```ts
const result = serviceCall()
// below did not result in VTL
if (result.cond) {
return result.a;
} else {
return result.b;
}
```
2. in-lined PropAccessExpr on a service call was ignored and broke the request mapping template
```ts
return serviceCall().prop
```
The request mapping template would mistakenly place the `.prop` reference on the request:
```
$util.toJson($v1.prop)
```
Now, the response mapping template contains that reference:
```
#set($context.stash.return__val = $context.result.prop)
```
3. the NoneDataSource required that the request mapping template was an object with `version` and `payload` properties.
```
{
"version": "2018-05-29",
"payload": null
}
```

fix: improve VTL synth to support if-statements after a service call and inline dereferencing of service call

---

.projen/deps.json
.projenrc.js
package.json
src/table.ts
test-app/package.json
test-app/yarn.lock
yarn.lock

Upgrades to latest `typesafe-dynamodb@0.1.5` version which includes breaking changes.

chore: upgrade to typesafe-dynamodb@0.1.5

---

src/compile.ts

Previous error message: `cannot parse declaration-only function: ${text}`
New error message: `Reflect does not support function references: ${text}`

fix: improve error message when reference is used in reflect

---

README.md
src/declaration.ts
src/expression.ts
src/function.ts
src/reflect.ts
src/table.ts
src/util.ts
test-app/src/people-db.ts
test/function.test.ts
test/vtl.test.ts

Fixes #42
Previously, Lambda Functions were defined with a type parameter that represented the function signature. Arguments were turned into objects using their names.
```ts
const myFunction = new Function<(arg1: string, arg2: number) => string>(...);
myFunction("some string", 10);
// actual json into the lambda
{
arg1: "some string:",
arg2: 10
}
```
This PR updates the function to accept a single Payload argument, matching the public lambda contract that accepts any single JSON input as a parameter.
```ts
const myFunction = new Function<{ arg1: string, arg2: number }, string>(...)
myFunction({ arg1: "some string", arg2: 10 });
```
The payload passed to the lambda function is the same as the above example.
The new representation allows for bare strings, numbers, and nulls.
```ts
const …
```

fix: update lambda function to accept json payload

---

src/assert.ts
src/compile.ts
src/expression.ts
src/function.ts
src/table.ts
src/vtl.ts
test/reflect.test.ts

Support positional arguments in methods with unknown names (any function, user defined interface, etc) by changing args to a array of `ArgumentExpr` instead of a Map.
Also pulls forward support for type casting (`x as any`, `<any>x`) and parenthesized expressions (`1 + (2 + 3)`) from the #39 PR.
```ts
const fn = assertNodeKind<FunctionDecl>(reflect(() => "".startsWith("")));
const return = assertNodeKind<RetunStmt>(fn.body.statements[0], "ReturnStmt");
const call = assertNodeKind<CallExpr>(return.expr, "CallExpr");
assertNodeType<StringLiteralExpr>(call.args.searchSearch, "StringLiteralExpr");
```
```ts
const fn = assertNodeKind<FunctionDecl>(reflect(() => "".startsWith("")));
const return = assertNodeKind<RetunStmt>(fn.body.statements[0], "ReturnStmt");
const call = …
```

feat: update call expr to have a list of ArgumentExpr. support parenthesis and type casting in compile.

---

src/compile.ts
src/expression.ts
src/vtl.ts
test/reflect.test.ts
test/vtl.test.ts

Closes #52
BREAKING CHANGE: Null and Undefined are now split into NullLiteralExpr and UndefinedLiteralExpr.
BREAKING CHANGE: PropertAssignExpr can contain a new expression node call ComputedPropertyNameExpr which contains any expression that can be used to assign a dynamic proeprty name on an object.

feat: split undefined, null, and support computed object names

---

src/appsync.ts
test/vtl.test.ts

While building a sample application, I noticed that `$util.time` was missing, which is extremely important for almost all use-cases. Quickly adding it in.
```ts
() => {
return $util.time.nowISO8601();
}
```

feat: add $util.time helpers to appsync

---

src/compile.ts

The exclude path glob `./src/{,**}/*` was not matching absolute source file paths like `/home/.../src/index.ts`.
Resolve the path with `path.resolve()`.

fix: bug where relative exclude paths do not match files

---

README.md
test-app/codegen.yml
test-app/package.json
test-app/schema.gql
test-app/src/generated-types.ts
test-app/src/people-db.ts
test-app/tsconfig.json
test-app/yarn.lock

This pull request adds graphql codegen to the test-app, this allows generating typescript code for all resolvers in the schema automatically.
Main benefit is that this ensures accurate types for the resolvers on any schema change
Discussion: 
I have added some documentation on this in the readme but I'm honestly not sure the end of the file is the best place to put this. Maybe creating a new readme in the test-app would make more sense?
We discussed this PR a while ago so I don't know if it still has it's place in this project or not but since I had already done the work I though I would still open it and discuss to see if it needs changes or if it would better live in an example repo I create.

chore: add graphql codegen typescript generation to test app

---

README.md
src/compile.ts
src/event-bridge/event-bus.ts
src/event-bridge/target.ts
test-app/src/message-board.ts
test/step-function.test.ts

Closes #48
Event Bridge Put Events API is one of the methods for putting new events on an event bus. We support some first party integrations between services and event bus.
Support (See issues for progress):
* Step Functions
* App Sync (coming soon #53)
* API Gateway (coming soon #50)
```ts
bus = new EventBus(stack, "bus");
new StepFunction<{ value: string }, void>((input) => {
bus({
detail: {
value: input.value,
},
});
});
```
This will create a step function which sends an event. It is also possible to send multiple events and use other Step Function logic.
> Limit: It is not currently possible to dynamically generate different numbers of events. All events sent must start from objects in the form `{ detail: ..., source: ... }` where all fields are optional.

feat(event-bridge, step-functions): step functions put event bridge events

---

README.md
src/compile.ts
src/event-bridge/event-bus.ts
src/event-bridge/event-pattern/synth.ts
src/event-bridge/rule.ts
src/event-bridge/target.ts
src/event-bridge/transform.ts
src/step-function.ts
test-app/src/message-board.ts
test/eventbus.test.ts
test/eventpattern.test.ts
test/step-function.test.ts
test/util.ts

Closes #71 Closes #99
Part Of #44 
Depends on PR #100 
`when` and `map` now correctly narrow the output type of the rule or transform. `when` narrowing requires type predicates, this is a typescript limitation. `(event): event is Type1 => 'field1' in event`
```ts
interface t1 {
type: "one",
value: string
}
interface t2 {
type: "two",
value: number
}
interface Event extends EventBusRuleInput<t1|t2>{}
const bus = new EventBus<Event>()
const rule1 = bus.when(this, 'rule1', (event):  event is Event<t1> => event.detail.type === "one" );
rule1.when(this, 'rule2', event => event.detail.value === "hello") // fine, value is a string
rule1.when(this, 'rule3', event => event.detail.value < 100) // fails, value in `t1` is a `string`, not a number
```
`when` can now be chained, representing multiple …

feat: step functions event source, `when` refining, `when` and `map` narrowing 

---

src/asl.ts

Fixing a simple bug found by snyk. In ASL, single quotes were not being properly replaced when creating JSON Path filter expressions.

fix: replace quote logic in ASL

---

src/asl.ts
test/step-function.test.ts

https://github.com/sam-goodwin/functionless/pull/125 was prematurely merged. It mistakenly used two backslashes instead of one and did not add any tests.

fix: replace single quotes in JSON Path filter expression with a single backslash

---

src/vtl.ts
test/vtl.test.ts

Fixes a weird but I ran into where `$obj.put('x', 1 + 1)` would cause a 500

fix(appsync): set a temporary variable for BinaryExpr inside an object put

---

website/src/pages/index.tsx

Minor tweak to branding from "no-ops cloud" to "Typesafe Cloud Programming". Still doesn't feel idea but good enough for now. "No-ops" was a bit too much of a lie.

chore: rebrand to Typesafe Cloud Programming

---

src/asl.ts
test/step-function.test.ts

Fixes #74
Support the `throw Error()` syntax, not just the `throw new Error()` in Step Functions (ASL).

feat: support throw Error() in Step Functions

---

.projen/tasks.json
.projenrc.js
.vscode/launch.json
scripts/compile-error-code-page.js
src/error-code.ts
src/index.ts
src/validate.ts
test/__snapshots__/validate.test.ts.snap
website/docs/error-codes.md
website/docusaurus.config.js
website/package.json

Fixes #176 
Adding an `error-code.ts` namespace where we will store all error code constants. Each error code has an ID, `code`, `messageText` and documentation in TypeScript code. 
```ts
export namespace ErrorCodes {
/**
* The computations that [Amazon States Language](https://docs.aws.amazon.com/step-functions/latest/dg/concepts-amazon-states-language.html)
* can do is restricted by JSON Path and the limited [Intrinsic Functions](https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-intrinsic-functions.html). Currently, arithmetic expressions are not supported.
* ```ts
* // ok
* new StepFunction(scope, id, () => 1 + 2);
*
* // illegal!
* new StepFunction(scope, id, (input: {num: number}) => input.number + 1);
* ```
*/
export const …
```

feat: provide link to documentation for compile time error codes

---

test/function.test.ts

Closes #198 
Tests to show that simple arrow functions work. 
#198 was likely caused by missing ts-patch and fixed by running ts-patch and then making any change to the file.

chore: more function compile tests

---

test/__snapshots__/step-function.test.ts.snap
test/step-function.test.ts
test/util.ts

Updating sfn tests to snapshot tests to reduce fragile tests on compiler changes.
Motivation - Large changes like #202 will cause major, mostly cosmetic changes to step function tests. Using snapshots will reduce time for author and PR reviewer.

feat: snapshot tests for step function compiler tests

---

.vscode/launch.json
.vscode/settings.json

Jest vscode plugin should reduce latency in debugging with jest. Turns off coverage during debugging.

chore: jest launch config

---

src/error-code.ts
src/validate.ts
test-app/tsconfig.json
test/__snapshots__/validate.test.ts.snap

Related to #220 
Automatically add functionless.org error code urls (auto generated) to synth errors with codes.
> SynthError: Expected input function to AppsyncResolver to be compiled by Functionless. Make sure you have the Functionless compiler plugin configured correctly.
>
> https://functionless.org/docs/error-codes#function-not-compiled-by-functionless-plugin

feat: error code urls.

---

test/__snapshots__/appsync.test.ts.snap
test/__snapshots__/function.test.ts.snap
test/__snapshots__/table.test.ts.snap
test/__snapshots__/vtl.test.ts.snap
test/appsync.test.ts
test/function.test.ts
test/step-function.test.ts
test/table.test.ts
test/util.ts
test/vtl.test.ts

Part of #202 
* Reduces the size and fragility of the app sync tests by outputting a snapshot instead of hand written evaluation.
* Wraps the template execution into a app sync single test method to support simpler tests
* Support matchObject to test granular cases like CDK tokens without the previous verbosity

chore: move app sync tests to snapshots

---

src/table.ts
test/table.test.ts

Fixes #253 
The `Table` and `ITable` types had a problem where type inference worked for `ITable` but not for `Table`. 
Also, `ITable<any, any, any>` was properly short-circuiting types.
Adding a `_brand` property to both `ITable` and `BaseTable` containing the type parameters fixed the error. I believe this is because it makes the type information readily accessible to the compiler which is maybe struggling to infer them out of the `getItem` calls.

fix: add _brand to ITable and BaseTable to fix type inference of$ AWS.DynamoDB.Table

---

src/api.ts
src/appsync.ts
src/asl.ts
src/aws.ts
src/declaration.ts
src/error.ts
src/event-bridge/event-bus.ts
src/event-bridge/event-pattern/synth.ts
src/event-bridge/target-input.ts
src/event-bridge/utils.ts
src/expression.ts
src/function.ts
src/guards.ts
src/index.ts
src/integration.ts
src/node.ts
src/statement.ts
src/step-function.ts
src/util.ts
src/visit.ts
src/vtl.ts
test/util.ts
website/docs/extending-functionless.md

Fixes #177
Move all type assertion functions to `src/guards.ts` to avoid circular imports.
Replace all uses of `.kind === "<kind>"` with the corresponding type assertion function.

chore(refactor): use type assertions instead of string comparisons

---

src/appsync.ts
src/asl.ts
src/compile.ts
src/guards.ts
src/integration.ts
src/step-function.ts
src/util.ts
src/visit.ts
test/__snapshots__/appsync.test.ts.snap
test/__snapshots__/step-function.test.ts.snap
test/__snapshots__/table.test.ts.snap
test/appsync.test.ts
test/step-function.test.ts
test/util.ts

Closes #212
Refactor step functions and app sync interpreters to refactor nested tasks to a normal form. This change will make the #202 easier by providing a generic interface for re-writing the AST tree. Async introduces more complex statements that need to be hoisted to a-normal form which would have been previously difficult.

fix: appsync and step function visitor hoist refactor

---

src/error-code.ts

Part of #285 
Remove the h3 from the error code documentation.

chore(docs): remove h3s for the workaround docs

---

.projen/tasks.json
.projenrc.js
src/appsync.ts
src/checker.ts
src/compile.ts
src/util.ts
src/validate.ts
test-app/cdk.json
test-app/message-board.gql
test-app/src/app.ts
test-app/src/message-board.ts
test-app/src/people-db.ts
test-app/src/people-events.ts
test/__snapshots__/validate.test.ts.snap
test/__snapshots__/vtl.test.ts.snap
test/appsync.test.ts
test/test-files/appsync.ts
test/util.ts
test/validate.test.ts
website/docs/concepts/appsync/code-generation.md
website/docs/concepts/appsync/supported-integrations.md
website/docs/concepts/appsync/usage.md

Fixes #137 
Fixes #65
```ts
export const getDeletionStatus = new AppsyncResolver<
{ executionArn: string },
string | undefined
>(stack, "getDeletionStatus", {
api,
typeName: "Query",
fieldName: "getDeletionStatus",
resolve: ($context) => {
const executionStatus = deleteWorkflow.describeExecution(
$context.arguments.executionArn
);
return executionStatus.status;
},
});
```
BREAKING CHANGE: AppsyncResolver is now a Construct and creates the resolvers within its constructor

feat(appsync): remove addResolver from AppsyncResolver and lazy template evaluation

---

src/table.ts
test-app/src/message-board.ts
test-app/src/people-db.ts
test/table.test.ts
website/docs/concepts/appsync/code-generation.md
website/docs/concepts/appsync/index.md
website/docs/concepts/appsync/supported-integrations.md
website/docs/concepts/appsync/usage.md
website/docs/concepts/table.md

Fixes #132 
The `Table` Resource used to expose Integrations, `getItem`, `putItem`, etc. that were only relevant to AWS Appsync Resolvers. This caused confusion where they were expected to be useful everywhere.
These appsync-specific integrations are now moved to the `appsync` property to more obviously represent this constraint.
Old behavior:
```ts
new AppsyncResolver(scope, id, () => {
return table.getItem(..);
});
```
New behavior:
```ts
new AppsyncResolver(scope, id, () => {
return table.appsync.getItem(..);
});
```
BREAKING CHANGE: Integration methods, `getItem`, `putItem`, `updateItem`, `deleteItem` and `query` on `Table` moved to `Table.appsync`.

feat(appsync, table): move appsync-specific methods on Table to a nested appsync property

---

.eslintrc.json
.projen/deps.json
.projenrc.js
package.json
scripts/localstack
test/function.localstack.test.ts
test/localstack.ts
yarn.lock

* @thantos forgot to remove `.only` from a test. Do that now
* add eslint rule to remove `.only`
* pin localstack cli version https://github.com/localstack/localstack/issues/6334
* run localstack tests

fix: remove .only on function test, pin localstack

---

.eslintrc.json
.projenrc.js
src/asl.ts
src/compile.ts
src/declaration.ts
src/util.ts
src/visit.ts
src/vtl.ts

Debugger statements will trigger for consumers as well. Enforce removing from code before push.

chore: no-debugger

---

.projenrc.js
package.json

Seeing 14m test runs, down from 18-30m

chore: turn off coverage for faster tests

---

src/api.ts
src/step-function.ts
test/__snapshots__/api.test.ts.snap
test/api.test.ts

Do things that don't scale?
```ts
new AwsMethod(
{
httpMethod: "POST",
resource: saga,
},
(
$input: ApiGatewayInput<
ApiRequest<
{},
Reservation & { [index: string]: ApiBody },
{ run_type?: RunType }
>
>
) => {
return sagaFunction.func({
input: {
reservation: $input.data!,
run_type: $input.params("run_type")!,
},
});
},
(result) => {
return result.data;
}
);
```
```velocity
{
"stateMachineArn":"arn:aws:states:us-east-1:180727192481:stateMachine:sagasagaFunction54D97EEF-B6WfpKLDY3QV",
"input":"{\"reservation\":$util.escapeJavaScript($input.json('$')),\"run_type\":\"$input.params('run_type')\"}"
}
```

fix: apig vtl stringify

---

src/declaration.ts
src/expression.ts
src/visit.ts

I had a merge issue that caused removed code from the previous branch (#347) to be carried into #363.
Also removed some other used code.

chore: remove unused code

---

src/api.ts
src/appsync.ts
src/asl.ts
src/aws.ts
src/compile.ts
src/declaration.ts
src/event-bridge/utils.ts
src/expression.ts
src/guards.ts
src/node.ts
src/step-function.ts
src/visit.ts
src/vtl.ts

Adds new AST nodes:
* `GetAccessorDecl`
* `SetAccessorDecl`
* `TaggedTemplateExpr`
* `OmittedExpr`
Allows `GetAccessorDecl`, `SetAccessorDecl` and `MethodDecl` in `ObjectLiteralExpr`.
```ts
const obj = {
get foo() { }
set foo(f) { }
method() { }
}
```
Add `isOptional` to `PropAccessExpr` and `CallExpr`.
```ts
call?.();
prop?.access;
```

feat: add GetAccessorDecl, SetAccessorDecl, TaggedTemplateExpr, OmittedExpr

---

src/asl.ts
src/checker.ts
src/compile.ts
src/event-bridge/target-input.ts
src/event-bridge/utils.ts
src/expression.ts
src/guards.ts
src/node-ctor.ts
src/node-kind.ts
src/node.ts
src/util.ts
src/vtl.ts

Fixes #373
Adds a new NodeKind, `QuasiString`, to represent the raw strings in a `TemplateExpr` and `TaggedTemplateExpr`:
```ts
const a = `quasi string ${expr}`
// parses as
new TemplateExpr(new Quasi("quasi string "), new Identifier("expr"))
```

feat: add QuasiString NodeKind for representing quasi strings in a TemplateExpr

---

src/api.ts
src/appsync.ts
src/asl.ts
src/checker.ts
src/compile.ts
src/expression.ts
src/function.ts
src/integration.ts
src/node-ctor.ts
src/node.ts
src/util.ts
src/visit.ts
src/vtl.ts
test/reflect.test.ts
test/s-expression.test.ts

Partial #374 
```ts
function foo() {
$AWS.DynamoDB.GetItem(..)
// before:
CallExpr(ReferenceExpr(() => $AWS.DynamoDB.GetItem), ..)
// now:
CallExpr(PropAccessExpr(GetItem, PropAccessExpr(DynamoDB, ReferenceExpr(() => $AWS)))
}
```

feat: remove logic in compile.ts to flatten references to expressions

---

src/expression.ts

When `yield*` is used (i.e. when `delegate` is `true` in a `YieldExpr`), then the `expr` must be defined, otherwise it can be `undefined`.
```ts
yield* <expr> // valid
yield*; // invalid
```

fix: enforce YieldExpr.expr is defined for yield*

---

.projen/deps.json
.projen/tasks.json
.projenrc.js
package.json
src/api.ts
src/appsync.ts
src/asl.ts
src/compile.ts
src/declaration.ts
src/error.ts
src/event-bridge/utils.ts
src/expression.ts
src/integration.ts
src/node.ts
src/s-expression.ts
src/span.ts
src/statement.ts
src/visit.ts
test-app/yarn.lock
test/node.test.ts
yarn.lock

Fixes #392 
This change adds a Node's Span information to each node.
```ts
/**
* A {@link Span} is a range of text within a source file, represented
* by two numbers, a `start` and `end` character position.
*/
export type Span = [
/**
* Character position where this span starts.
*/
start: number,
/**
* Character position where this span ends.
*/
end: number
];
```
Because a span 2-tuple looks identical to a Node's s-expression `[kind: number, ...args]`, we adopt the convention of the span always being the element directly following the `kind`, making the definition of a s-expression now:
```ts
export type SExpr = [kind: number, span: Span, ...args: any[]]
```

feat: add Span information to F-AST

---

src/declaration.ts
src/expression.ts

This changes adds the __filename to the root nodes:
* ClassDecl
* ClassExpr
* MethodDecl
* ConstructorDecl
* FunctionDecl
* FunctionExpr
* ArrowFunctionExpr
* GetAccessorDecl
* SetAccessorDecl

feat: add filename to root AST nodes

---

src/compile.ts
src/declaration.ts
src/expression.ts

For consistency, we will use `Identifier` instead of `string` for all names in the AST. This change updates ClassDecl and ClassExpr. They are not used so the change is not impactful on any existing code.

feat(ast): update ClassDecl.name and ClassExpr.name to be an Identifier

---

.projen/tasks.json
.projenrc.ts

Builds are failing because node is running out of memory. To mitigate, this change increases the memory from 2GB to 8GB on the compile and test tasks.

chore: increase allowed memory of node process

---

src/function-prewarm.ts
test/__snapshots__/serialize.test.ts.snap

Running Functions with 128MB of memory was failing because `require("aws-sdk")` uses 150MB of memory. This change updates the pre-warm to import specific clients, e.g. `require("aws-sdk/clients/dynamodb")` which significantly reduces the memory usage. It should also make cold starts faster.

fix: update PreWarm to require individual clients to minimize memory usage

---

.projen/tasks.json
.projenrc.ts
src/step-function.ts
test/__snapshots__/step-function.localstack.test.ts.snap
test/step-function.localstack.test.ts

fix(step-functions): props are not correctly passed to step function

---

.projen/deps.json
.projen/tasks.json
.projenrc.ts
package.json
test-app/package.json
test-app/yarn.lock
yarn.lock

SWC plugins have a semver problem where subsequent releases of swc_* packages broke plugins that weren't built against the latest version. 
SWC recently released a refactor where `swc_core` is used as an intermediate interface for backwards compatibility. This change upgrades our dependencies to the latest `@swc/core` and `@swc/cli`.
Depends on https://github.com/functionless/ast-reflection/pull/24
BREAKING CHANGE: requires all consumers updated to @swc/core@^1.2.244

fix: upgrade to latest SWC compatible with new swc_core

---

.projen/deps.json
.projen/tasks.json
.projenrc.ts
package.json
test-app/package.json
test-app/yarn.lock
yarn.lock

Getting seg faults once 1.2.245 was released. Cleaning up ast-reflection (https://github.com/functionless/ast-reflection/pull/25) and bumping the swc/core versions in functionless.

fix: upgrade to swc/core 1.2.245

---

src/aws-sdk/sdk.ts
src/error-code.ts
test/step-function.localstack.test.ts
test/step-function.test.ts
test/validate.test.ts

Fixes #454 
Partial #443
Friendly error when unsupported SFN integration APIs are used.
https://docs.aws.amazon.com/step-functions/latest/dg/supported-services-awssdk.html

fix(step-functions): fail gracefully on unsupported APIs

---

.projenrc.ts
tsconfig.dev.json
tsconfig.json

Decreases memory consumption and type checking execution time:
**Before:**
```
> functionless git:(tyler/api-gateway) time npx tsc --noEmit --extendedDiagnostics
Files:                         2091
Lines of Library:             26877
Lines of Definitions:       1082757
Lines of TypeScript:         112999
Lines of JavaScript:              0
Lines of JSON:                    0
Lines of Other:                   0
Nodes of Library:            117549
Nodes of Definitions:       2827454
Nodes of TypeScript:         375598
Nodes of JavaScript:              0
Nodes of JSON:                    0
Nodes of Other:                   0
Identifiers:                1215345
Symbols:                     980049
Types:                       484854
Instantiations:              239430
Memory used: …
```

chore(projen): add skipLibCheck to tsconfigs

---

src/asl/asl-graph.ts
src/asl/synth.ts
src/aws.ts
src/checker.ts
src/validate.ts

Shaved a second off of `tsc` compile time with minor changes.
Before
```
Files:                         2091
Lines of Library:             26877
Lines of Definitions:       1082757
Lines of TypeScript:         112992
Lines of JavaScript:              0
Lines of JSON:                    0
Lines of Other:                   0
Nodes of Library:            117549
Nodes of Definitions:       2827454
Nodes of TypeScript:         375577
Nodes of JavaScript:              0
Nodes of JSON:                    0
Nodes of Other:                   0
Identifiers:                1215338
Symbols:                     781809
Types:                       130148
Instantiations:              164248
Memory used:               1188875K
Assignability cache size:     37718
Identity cache size:           8734 …
```

chore: reduce computational complexity of types

---

.projen/deps.json
.projenrc.ts
package.json
src/expression.ts
src/node.ts
src/step-function.ts
src/table.ts
website/package.json
website/yarn.lock
yarn.lock

Fixes type issues which broke in TS 4.8.
Resolved a complex type that was causing an extra second of processing.
Total time:                  16.91s
```ts
if (this.parent === undefined) {
return undefined;
} else if (is(this.parent)) {
return this.parent;
} else {
return this.parent.findParent(is);
}
```
Total time:                  16.03s
```ts
if (this.parent === undefined) {
return undefined;
} else if (is(this.parent)) {
return this.parent as unknown as N;
} else {
return this.parent.findParent(is);
}
```
Evaluating `Parent & {} & N` was taking a second
```
Hot Spots
├─ Check file /home/sussmans/functionless/src/node.ts (1741ms)
│  └─ Compare types 7794 and 1985 (1125ms)
│     └─ Compare types 7794 and 9 (1125ms)
│        ├─ {"id":7794,"kind":"Intersection","count":3,"types":[838,33,19 …
```

chore: upgrade typescript to 4.8, improve compile performance

---

scripts/localstack

Localstack is failing to start due to changes in pip that github actions has not patched yet.
https://askubuntu.com/questions/1428181/module-lib-has-no-attribute-x509-v-flag-cb-issuer-check

chore: force pyOpenSSL to upgrade

---

src/api.ts
src/appsync.ts
src/asl/synth.ts
src/declaration.ts
src/expression.ts
src/integration.ts
src/node.ts
src/span.ts
src/statement.ts
src/vtl.ts

Partial https://github.com/functionless/functionless/issues/374
```ts
while (true) <stmt>
``` 
```ts
call.?(..args)
```

fix: ForOfStmt, ForInStmt, ForStmt, WhileStmt, DoStmt ES conformance

---

.projen/deps.json
.projenrc.ts
package.json
src/asl/synth.ts
src/statement.ts
src/vtl.ts
test-app/yarn.lock
yarn.lock

Upgrade to ast-reflection@0.3.1 and remove VariableDecl from ForOfStmt and ForInStmt
BREAKING CHANGE: ForOfStmt and ForInStmt now only accept VariableDeclList for the initializer.

chore: remove backwards compatible VariableDecl in ForOfStmt and ForInStmt

---

src/reflect.ts

Undefined function declarations would throw a confusing error
> Expected input function to [] to be compiled by Functionless
Instead return a more friendly message that the function is undefined.
> Expected input function to [] to be present, received undefined.

fix: improve error when function is undefined

---

test/runtime.ts

Release is failing because the creds were set to live for 30 min and the tests were taking 40+ minutes, increasing to 1 hour.
Updated deployment flag:
1. force - false, will not try to deploy if one isn't needed, should reduce churn with multiple commits on the same branch
2. hotswap - should try to push out new lambda and sfn definitions when they are the only part that changes

fix: increase assume role lifetime and CDK deploy change flags

---

src/event-bridge/event-bus.ts
src/function.ts
src/integration.ts
src/queue.ts
src/step-function.ts
test/eventpattern.test.ts

Remove the hacky EventBusIntegration type argument from the Integration type.

chore: remove auxillary EventBusIntegration type argument from Integration type

---

.projen/tasks.json
.projenrc.ts
src/event-bridge/event-bus.ts
src/event-bridge/rule.ts
src/event-bridge/target-input.ts
src/event-bridge/transform.ts
src/function.ts
src/integration.ts
src/queue.ts
src/step-function.ts
test/__snapshots__/validate.test.ts.snap
test/appsync.test.ts
test/eventpattern.test.ts
test/eventtargets.test.ts
test/function.test.ts
test/node.test.ts
test/step-function.localstack.test.ts
test/step-function.test.ts
test/table.test.ts
test/test-files/step-function.ts
test/util.ts
test/vtl.test.ts

fix: infer type of Function inlined inside EventBus.pipe

---

package.json
packages/core/.eslintrc.js
packages/core/package.json
packages/core/scripts/run-task
yarn.lock

Projen eject does not include the necessary dependencies for the release task.

fix: release task failing due to missing projen dep

---

apps/test-app/package.json
apps/website/package.json
apps/website/tsconfig.json
package.json
packages/functionless/package.json
packages/functionless/tsconfig.json
scripts/doctor-aggregate-packages.mjs

@functionless/test (which is a private package) was in our public package's dependencies

chore: remove private dependencies from aggregate packages

---

packages/@functionless/register/package.json
packages/create-functionless/src/util.ts
packages/create-functionless/templates/base/.gitignore.template
packages/create-functionless/templates/base/manifest.json

`create-functionless` does not add @swc/core by default.
```
thread '<unnamed>' panicked at 'called Result::unwrap() on an Err value: LayoutError', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.37/src/impls/core/mod.rs:265:67
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/home/sussmans/functionless-bot/src/create-todo.ts")'
```
Also added `.fl/` to the default git ignore.

chore: add @swc/core as a peer depdendency
