src/vtl.ts
test/vtl.test.ts
yarn.lock

When a map precedes a `reduce`, `forEach`, or a `map`, apply the map transformations inline in the same VTL foreach.
Example
```ts
reflect((context: AppsyncContext<{ list: string[] }>) => {
return context.arguments.list
.map((item) => `hello ${item}`)
.map((item) => `hello ${item}`);
})
```
Before:
```vtl
#set($v1 = [])
#set($v2 = [])
#foreach($item in $context.arguments.list)
#set($v3 = "hello \${item}")
$util.qr($v2.add($v3))
#end
#foreach($item in $v2)
#set($v4 = "hello \${item}")
$util.qr($v1.add($v4))
#end
...
```
After
```vtl
#set($v1 = [])
#foreach($item in $context.arguments.list)
#set($item = "hello \${item}")
#set($v2 = "hello \${item}")
$util.qr($v1.add($v2))
#end
```
Caveat: When the map, reduce, or foreach uses the array parameter, do not flatten.
Bug: Fixed a bug in reduce …

feat: flatten chained map, forEach and reduce for vtl

---

src/vtl.ts
test/function.test.ts
test/vtl.test.ts

fix(appsync): use temp variables for all BinaryExpr and UnaryExpr nodes

---

src/asl.ts
src/event-bridge/event-bus.ts
src/event-bridge/event-pattern/synth.ts
test/eventpattern.test.ts
test/eventtargets.test.ts
test/vtl.test.ts
website/docs/concepts/appsync/supported-integrations.md
website/docs/concepts/appsync/syntax.md
website/docs/concepts/appsync/usage.md
website/docs/concepts/aws.md
website/docs/concepts/event-bridge/event-bus.md
website/docs/concepts/function.md
website/docs/concepts/step-function/syntax.md
website/docs/concepts/table.md
website/docusaurus.config.js

Update all of current github referenced to use the new path from: #143

chore: update repo reference

---

src/appsync.ts
test/__snapshots__/vtl.test.ts.snap
test/vtl.test.ts

feat: VTL util.log types

---

.projenrc.js
package.json

chore: add descrption to package.json

---

src/table.ts
test/__snapshots__/table.test.ts.snap
test/table.test.ts

Sort field undefined handling was inverted.

fix: fix sort field type in dynamo table

---

src/appsync.ts
src/asl.ts
src/checker.ts
src/compile.ts
src/declaration.ts
src/error-code.ts
src/event-bridge/event-pattern/synth.ts
src/event-bridge/target-input.ts
src/event-bridge/utils.ts
src/expression.ts
src/guards.ts
src/node.ts
src/statement.ts
src/validate.ts
src/visit.ts
src/vtl.ts
test/__snapshots__/api.test.ts.snap
test/__snapshots__/appsync.test.ts.snap
test/__snapshots__/step-function.test.ts.snap
test/__snapshots__/validate.test.ts.snap
test/__snapshots__/vtl.test.ts.snap
test/appsync.test.ts
test/test-files/appsync.ts
test/util.ts
test/vtl.test.ts

Closes #266 Closes #265 Closes #150 Closes #8 Closes #235 Closes #300
Partial #232
* #232 
* Sync - New PR

fix(appsync): various appsync and related bugs

---

src/asl.ts
src/aws.ts
src/event-bridge/event-bus.ts
src/function.ts
src/step-function.ts
test/__snapshots__/step-function.localstack.test.ts.snap
test/__snapshots__/step-function.test.ts.snap
test/step-function.localstack.test.ts
test/step-function.test.ts

* Move the input to a context variable in the machine.
* Prepares step functions for #68

feat(step-functions): move input to dynamic context

---

yarn.lock

chore: upgrade appsync sym and moment to make dependabot happy

---

src/api.ts
src/appsync.ts
src/asl.ts
src/checker.ts
src/compile.ts
src/error-code.ts
src/expression.ts
src/function.ts
src/integration.ts
src/node.ts
src/util.ts
src/validate.ts
src/vtl.ts
test/__snapshots__/step-function.localstack.test.ts.snap
test/__snapshots__/step-function.test.ts.snap
test/__snapshots__/validate.test.ts.snap
test/step-function.localstack.test.ts
test/step-function.test.ts
test/test-files/api-gateway.ts
test/test-files/appsync.ts

Closes #281 Closes #210 Closes #78 Closes #73
Partial #84
* `join`
* ternary
* bug: out of scope in map states
* removed most of the `skip`s in step function tests.

feat(step-functions): ternary, join, bug fixes

---

src/asl.ts
src/aws.ts
src/event-bridge/event-bus.ts
src/step-function.ts

chore: make Next or End required for applicable states

---

.projenrc.ts
.swcrc
test/__snapshots__/serialize.test.ts.snap

SWC can generate a ton of whitespace without minify:true, this may be causing problems. Setting to minify true is a quick workaround.

chore: configure minify:true for performance

---

src/asl.ts
test/__snapshots__/step-function.localstack.test.ts.snap
test/__snapshots__/step-function.test.ts.snap
test/step-function.localstack.test.ts
test/step-function.test.ts

* ~~in-order evaluation approach~~

fix(step-functions): assignment during literal can use the wrong values

---

src/aws.ts
test/function.test.ts

fix: support PropAccessExpr and ElementAccessExpr for .DynamoDB.*

---

src/aws-sdk/iam.ts
yarn.lock

Updated dependencies and detected a new service, ControlTower. Adding to IAM_SERVICE_PREFIX

feat: add ControlTower to IAM_SERVICE_PREFIX

---

src/error-code.ts
src/step-function.ts
test/__snapshots__/step-function.localstack.test.ts.snap
test/step-function.localstack.test.ts
test/validate.test.ts

Closes #486 
```ts
$SFN.retry(async () => {
return await func();
});
$SFN.retry([{ ErrorEquals: ["MyError"], MaxAttempts: 2, IntervalSeconds: 4, BackoffRate: 1 }], async () => {
throw new StepFunctionError("MyError", "cause");
});
```

feat: step functions retry

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/upgrade-main.yml
.projenrc.ts

Attempt to fix: https://github.com/functionless/functionless/runs/8297344708?check_suite_focus=true

fix: github workflows permissions

---

.github/workflows/close.yml
.projenrc.ts

https://github.com/functionless/functionless/pull/502#issuecomment-1246758663

fix: bug in the close workflow

---

src/asl/synth.ts
src/util.ts
test/__snapshots__/step-function.localstack.test.ts.snap
test/step-function.localstack.test.ts
website/docs/concepts/step-function/usage.md

feat(step-functions): support string.split

---

website/src/components/home/features/asides/upgrade.tsx
website/src/components/home/features/featureSection.tsx
website/src/components/home/features/index.tsx
website/src/components/home/hero.tsx
website/src/content/home/nav.ts
website/src/css/custom.css
website/src/theme/Navbar/Content/index.tsx
website/src/theme/Navbar/Logo/index.tsx
website/src/theme/Navbar/MobileSidebar/Header/index.tsx

- Fixes logo and overscroll on iphone.
- Makes hero buttons stack vertically on small screens.
- Fix consistency of mobile/desktop nav menu switching

fix(website): Improve iphone layout

---

packages/core/package.json
packages/fl-exp/package.json

chore: set publishConfig in core and fl-exp

---

.github/workflows/release.yml

chore: limit release concurrency

---

.github/workflows/build.yml
apps/fl-exp-simple/tsconfig.json
apps/test-app/tsconfig.json
apps/website/package.json
apps/website/tsconfig.json
package.json
packages/@functionless/ast/package.json
packages/@functionless/aws-constructs/package.json
packages/@functionless/aws-util/package.json
packages/@functionless/aws/package.json
packages/@functionless/aws/tsconfig.json
packages/@functionless/fl-exp/package.json
packages/@functionless/fl-exp/tsconfig.json
packages/@functionless/util/package.json
tsconfig.json
turbo.json
yarn.lock

chore: use tsc -b for build and run with turbo

---

.github/actions/build/action.yml
.gitignore

chore: install with frozen lockfile and ignore ci-generated files

---

packages/create-functionless/package.json

fix: update project to reflect lib as outdir

---

package.json
yarn.lock

The release task failed because `yarn test:smoke` doesn't exist. Added in that task.

fix: add test:smoke command

---

.github/actions/build/action.yml
.github/workflows/build.yml
.github/workflows/close.yml
.github/workflows/pull-request-lint.yml
packages/create-functionless/package.json

chore: improve cache lookup to favor test caches

---

package.json

fix: disable smoke test as it is entirely broken

---

apps/website/docusaurus.config.js

chore: set up google analytics

---

.github/actions/build/action.yml

chore: fail fast when unstaged changes are detected

---

scripts/doctor-aggregate-packages.mjs

fix: prevent overwrite on existing packages

---

packages/create-functionless/package.json

fix: esbuild should output to lib

---

packages/@functionless/aws-lambda/src/function.ts
packages/@functionless/cli/src/synthesize.ts

fix(devx): support lambda props and env

---

packages/create-functionless/templates/base/.gitignore.template
packages/create-functionless/templates/base/package.json.template
packages/create-functionless/templates/base/tsconfig.json

tsconfig was missing output config and missing watch command

fix: create-functionless ts output config and gitignore
